runtime: go
api_version: go1

handlers:
- url: /.*
  script: _go_app

env_variables:
  # Replace INSTANCE_CONNECTION_NAME with the value obtained when configuring your
  # Cloud SQL instance, available from the Google Cloud Console or from the Cloud SDK.
  # For Cloud SQL 2nd generation instances, this should be in the form of "project:region:instance".
  CLOUDSQL_CONNECTION_NAME: project-alpha-170622:us-central1:sessions
  # Replace username and password if you aren't using the root user.
  CLOUDSQL_USER: root
  CLOUDSQL_PASSWORD: 'roialpha'
  ROI-HASHKEY: 'qpzmgjf82'
  ROI-BLOCKKEY: '1kJ8l1E6ZF3KEXL8'
  DEBUG-MODE: 'true'